
export const unsortedReimbursements = [
  {
    id: 1,
    description: "Client dinner at Restaurant ABC",
    amount: 145.5,
    date: "Nov 12, 2024",
    employee: "Sarah Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah-chen",
    department: { departmentName: "Sales", departmentId: 1 },
    status: "pending",
    category: "Meals & Entertainment",
    hasReceipt: true,
  },
  {
    id: 2,
    description: "Uber rides for business meetings",
    amount: 67.25,
    date: "Nov 10, 2024",
    employee: "Michael Rodriguez",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=michael-rodriguez",
    department: { departmentName: "Marketing", departmentId: 2 },
    status: "approved",
    category: "Transportation",
    hasReceipt: true,
  },
  {
    id: 3,
    description: "Office supplies from Staples",
    amount: 89.99,
    date: "Nov 8, 2024",
    employee: "Emma Thompson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma-thompson",
    department: { departmentName: "Operations", departmentId: 3 },
    status: "declined",
    category: "Office Supplies",
    hasReceipt: false,
  },
  {
    id: 4,
    description: "Hotel stay for conference",
    amount: 299.99,
    date: "Nov 5, 2024",
    employee: "John Smith",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john-smith",
    department: { departmentName: "Finance", departmentId: 4 },
    status: "approved",
    category: "Travel",
    hasReceipt: true,
  },
  {
    id: 5,
    description: "Software license renewal",
    amount: 199.99,
    date: "Nov 3, 2024",
    employee: "Lisa Wang",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=lisa-wang",
    department: { departmentName: "IT", departmentId: 5 },
    status: "pending",
    category: "Software",
    hasReceipt: true,
  },
  {
    id: 6,
    description: "Client dinner at Restaurant ABC",
    amount: 145.5,
    date: "Nov 12, 2024",
    employee: "Sarah Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah-chen",
    department: { departmentName: "Sales", departmentId: 1 },
    status: "pending",
    category: "Meals & Entertainment",
    hasReceipt: true,
  },
  {
    id: 7,
    description: "Uber rides for business meetings",
    amount: 67.25,
    date: "Nov 10, 2024",
    employee: "Michael Rodriguez",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=michael-rodriguez",
    department: { departmentName: "Marketing", departmentId: 2 },
    status: "approved",
    category: "Transportation",
    hasReceipt: true,
  },
  {
    id: 8,
    description: "Office supplies from Staples",
    amount: 89.99,
    date: "Nov 8, 2024",
    employee: "Emma Thompson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma-thompson",
    department: { departmentName: "Operations", departmentId: 3 },
    status: "draft",
    category: "Office Supplies",
    hasReceipt: false,
  },
  {
    id: 9,
    description: "Hotel stay for conference",
    amount: 299.99,
    date: "Nov 5, 2024",
    employee: "John Smith",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john-smith",
    department: { departmentName: "Finance", departmentId: 4 },
    status: "paid",
    category: "Travel",
    hasReceipt: true,
  },
  {
    id: 10,
    description: "Software license renewal",
    amount: 199.99,
    date: "Nov 3, 2024",
    employee: "Lisa Wang",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=lisa-wang",
    department: { departmentName: "IT", departmentId: 5 },
    status: "pending",
    category: "Software",
    hasReceipt: true,
  },
  {
    id: 11,
    description: "Flight and accommodation for client visit",
    amount: 2450.75,
    date: "Nov 15, 2024",
    employee: "David Martinez",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=david-martinez",
    department: { departmentName: "Sales", departmentId: 1 },
    status: "approved",
    category: "Travel",
    hasReceipt: true,
  },
  {
    id: 12,
    description: "Annual team retreat accommodation",
    amount: 3200.0,
    date: "Nov 20, 2024",
    employee: "Jessica Lee",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jessica-lee",
    department: { departmentName: "Operations", departmentId: 3 },
    status: "pending",
    category: "Travel",
    hasReceipt: false,
  },
  {
    id: 13,
    description: "Enterprise software platform subscription",
    amount: 5999.99,
    date: "Nov 18, 2024",
    employee: "Robert Taylor",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=robert-taylor",
    department: { departmentName: "IT", departmentId: 5 },
    status: "approved",
    category: "Software",
    hasReceipt: true,
  },
  {
    id: 14,
    description: "Office furniture and equipment setup",
    amount: 8500.0,
    date: "Nov 22, 2024",
    employee: "Amanda White",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=amanda-white",
    department: { departmentName: "Operations", departmentId: 3 },
    status: "pending",
    category: "Office Equipment",
    hasReceipt: true,
  },
  // Batch expenses for Goodness Swift
  {
    id: 15,
    description: "Lunch with Clients",
    amount: 3000.0,
    date: "13 May 2025",
    employee: "Goodness Swift",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=goodness-swift",
    department: { departmentName: "Marketing", departmentId: 2 },
    status: "approved",
    category: "Meals & Entertainment",
    hasReceipt: true,
  },
  {
    id: 16,
    description: "Lunch with Clients",
    amount: 3000.0,
    date: "09 Sep 2025",
    employee: "Goodness Swift",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=goodness-swift",
    department: { departmentName: "Marketing", departmentId: 2 },
    status: "declined",
    category: "Meals & Entertainment",
    hasReceipt: true,
  },
  {
    id: 17,
    description: "Lunch with Clients",
    amount: 3000.0,
    date: "17 Jul 2025",
    employee: "Goodness Swift",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=goodness-swift",
    department: { departmentName: "Marketing", departmentId: 2 },
    status: "approved",
    category: "Meals & Entertainment",
    hasReceipt: true,
  },
  {
    id: 18,
    description: "Lunch with Clients",
    amount: 3000.0,
    date: "15 Oct 2025",
    employee: "Goodness Swift",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=goodness-swift",
    department: { departmentName: "Marketing", departmentId: 2 },
    status: "pending",
    category: "Meals & Entertainment",
    hasReceipt: true,
  },
  // Batch expenses for Sarah Chen
  {
    id: 19,
    description: "Trip to Abuja",
    amount: 1500.0,
    date: "20 Oct 2024",
    employee: "Sarah Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah-chen",
    department: { departmentName: "Sales", departmentId: 1 },
    status: "pending",
    category: "Travel",
    hasReceipt: true,
  },
  {
    id: 20,
    description: "Trip to Abuja",
    amount: 2400.0,
    date: "5 Jan 2026",
    employee: "Sarah Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah-chen",
    department: { departmentName: "Sales", departmentId: 1 },
    status: "approved",
    category: "Travel",
    hasReceipt: true,
  },
  {
    id: 21,
    description: "Trip to Abuja",
    amount: 2900.0,
    date: "21 Feb 2025",
    employee: "Sarah Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah-chen",
    department: { departmentName: "Sales", departmentId: 1 },
    status: "declined",
    category: "Travel",
    hasReceipt: true,
  },
  {
    id: 22,
    description: "Trip to Abuja",
    amount: 2500.0,
    date: "20 Oct 2025",
    employee: "Sarah Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah-chen",
    department: { departmentName: "Sales", departmentId: 1 },
    status: "pending",
    category: "Travel",
    hasReceipt: true,
  },
  // Batch expenses for Michael Rodriguez
  {
    id: 23,
    description: "Software Subscription",
    amount: 1500.0,
    date: "27 Aug 2025",
    employee: "Michael Rodriguez",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=michael-rodriguez",
    department: { departmentName: "Marketing", departmentId: 2 },
    status: "approved",
    category: "Software Subscription",
    hasReceipt: true,
  },
  {
    id: 24,
    description: "Software Subscription",
    amount: 2000.0,
    date: "06 Jun 2025",
    employee: "Michael Rodriguez",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=michael-rodriguez",
    department: { departmentName: "Marketing", departmentId: 2 },
    status: "pending",
    category: "Software Subscription",
    hasReceipt: true,
  },
  {
    id: 25,
    description: "Software Subscription",
    amount: 4500.0,
    date: "10 Mar 2025",
    employee: "Michael Rodriguez",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=michael-rodriguez",
    department: { departmentName: "Marketing", departmentId: 2 },
    status: "approved",
    category: "Software Subscription",
    hasReceipt: true,
  },
  {
    id: 26,
    description: "Software Subscription",
    amount: 3300.0,
    date: "18 Oct 2025",
    employee: "Michael Rodriguez",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=michael-rodriguez",
    department: { departmentName: "Marketing", departmentId: 2 },
    status: "declined",
    category: "Software Subscription",
    hasReceipt: true,
  },
  // Batch expenses for Emma Thompson
  {
    id: 27,
    description: "Conference Expenses",
    amount: 1500.0,
    date: "11 Dec 2025",
    employee: "Emma Thompson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma-thompson",
    department: { departmentName: "Operations", departmentId: 3 },
    status: "pending",
    category: "Travel",
    hasReceipt: true,
  },
  {
    id: 28,
    description: "Conference Expenses",
    amount: 2800.0,
    date: "2 Apr 2025",
    employee: "Emma Thompson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma-thompson",
    department: { departmentName: "Operations", departmentId: 3 },
    status: "approved",
    category: "Travel",
    hasReceipt: true,
  },
  {
    id: 29,
    description: "Conference Expenses",
    amount: 3000.0,
    date: "22 Oct 2025",
    employee: "Emma Thompson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma-thompson",
    department: { departmentName: "Operations", departmentId: 3 },
    status: "pending",
    category: "Travel",
    hasReceipt: true,
  },
];

// Helper function to parse date strings and convert to Date object
const parseDate = (dateStr: string): Date => {
  // Handle formats like "Nov 12, 2024" and "15 Oct 2025"
  return new Date(dateStr);
};

// Sort reimbursements by date from most recent to oldest
export const reimbursements = unsortedReimbursements.sort((a, b) => {
  return parseDate(b.date).getTime() - parseDate(a.date).getTime();
});

export type Reimbursement = (typeof reimbursements)[0];
