// lib/permissions.ts

// Define available permissions
export const PERMISSIONS = {
  // Dashboard
  VIEW_DASHBOARD: 'view_dashboard',
  VIEW_ADMIN_DASHBOARD: "view_admin_dashboard",
  VIEW_EMPLOYEE_DASHBOARD: "view_employee_dashboard",

  // Expenses
  VIEW_EXPENSES: 'view_expenses',
  VIEW_CARD_TRANSACTIONS: 'view_card_transactions',
  VIEW_REIMBURSEMENTS: 'view_reimbursements',
  VIEW_TRAVEL_EXPENSES: 'view_travel_expenses',

  // Other modules
  VIEW_CARDS: 'view_cards',
  VIEW_SPEND_PROGRAMS: 'view_spend_programs',
  VIEW_PROCUREMENT: 'view_procurement',
  VIEW_BILL_PAY: 'view_bill_pay',
  VIEW_ACCOUNTING: 'view_accounting',
  VIEW_BUSINESS_ACCOUNT: 'view_business_account',
  VIEW_PEOPLE: 'view_people',
  VIEW_VENDORS: 'view_vendors',

  // Settings
  VIEW_SETTINGS: 'view_settings',
  MANAGE_EXPENSE_POLICY: 'manage_expense_policy',
  MANAGE_COMPANY_SETTINGS: 'manage_company_settings',
  MANAGE_ENTITIES: 'manage_entities',
  MANAGE_APPS: 'manage_apps',
  MANAGE_PERSONAL_SETTINGS: 'manage_personal_settings',

  // Special
  VIEW_HELP: 'view_help',
  VIEW_INBOX: 'view_inbox',
  VIEW_INSIGHTS: 'view_insights',
} as const;

// Define role permissions mapping
export type UserRole =
  | 'owner'
  | 'admin'
  | 'manager'
  | 'auditor'
  | 'employee';

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  owner: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_EXPENSES,
    PERMISSIONS.VIEW_CARD_TRANSACTIONS,
    PERMISSIONS.VIEW_REIMBURSEMENTS,
    PERMISSIONS.VIEW_TRAVEL_EXPENSES,
    PERMISSIONS.VIEW_CARDS,
    PERMISSIONS.VIEW_SPEND_PROGRAMS,
    PERMISSIONS.VIEW_PROCUREMENT,
    PERMISSIONS.VIEW_BILL_PAY,
    PERMISSIONS.VIEW_ACCOUNTING,
    PERMISSIONS.VIEW_BUSINESS_ACCOUNT,
    PERMISSIONS.VIEW_PEOPLE,
    PERMISSIONS.VIEW_VENDORS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.MANAGE_EXPENSE_POLICY,
    PERMISSIONS.MANAGE_COMPANY_SETTINGS,
    PERMISSIONS.MANAGE_ENTITIES,
    PERMISSIONS.MANAGE_APPS,
    PERMISSIONS.MANAGE_PERSONAL_SETTINGS,
    PERMISSIONS.VIEW_HELP,
    PERMISSIONS.VIEW_INBOX,
    PERMISSIONS.VIEW_INSIGHTS,
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
  ],
  admin: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_EXPENSES,
    PERMISSIONS.VIEW_CARD_TRANSACTIONS,
    PERMISSIONS.VIEW_REIMBURSEMENTS,
    PERMISSIONS.VIEW_TRAVEL_EXPENSES,
    PERMISSIONS.VIEW_CARDS,
    PERMISSIONS.VIEW_SPEND_PROGRAMS,
    PERMISSIONS.VIEW_PROCUREMENT,
    PERMISSIONS.VIEW_BILL_PAY,
    PERMISSIONS.VIEW_ACCOUNTING,
    PERMISSIONS.VIEW_BUSINESS_ACCOUNT,
    PERMISSIONS.VIEW_PEOPLE,
    PERMISSIONS.VIEW_VENDORS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.MANAGE_EXPENSE_POLICY,
    PERMISSIONS.MANAGE_ENTITIES,
    PERMISSIONS.MANAGE_APPS,
    PERMISSIONS.MANAGE_PERSONAL_SETTINGS,
    PERMISSIONS.VIEW_HELP,
    PERMISSIONS.VIEW_INBOX,
    PERMISSIONS.VIEW_INSIGHTS,
  ],
  manager: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_EXPENSES,
    PERMISSIONS.VIEW_CARD_TRANSACTIONS,
    PERMISSIONS.VIEW_REIMBURSEMENTS,
    PERMISSIONS.VIEW_TRAVEL_EXPENSES,
    PERMISSIONS.VIEW_CARDS,
    PERMISSIONS.VIEW_SPEND_PROGRAMS,
    PERMISSIONS.VIEW_PROCUREMENT,
    PERMISSIONS.VIEW_BILL_PAY,
    PERMISSIONS.VIEW_ACCOUNTING,
    PERMISSIONS.VIEW_BUSINESS_ACCOUNT,
    PERMISSIONS.VIEW_VENDORS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.MANAGE_PERSONAL_SETTINGS,
    PERMISSIONS.VIEW_HELP,
    PERMISSIONS.VIEW_INBOX,
    PERMISSIONS.VIEW_INSIGHTS,
  ],
  auditor: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_EXPENSES,
    PERMISSIONS.VIEW_CARD_TRANSACTIONS,
    PERMISSIONS.VIEW_REIMBURSEMENTS,
    PERMISSIONS.VIEW_TRAVEL_EXPENSES,
    PERMISSIONS.VIEW_CARDS,
    PERMISSIONS.VIEW_ACCOUNTING,
    PERMISSIONS.VIEW_BUSINESS_ACCOUNT,
    PERMISSIONS.VIEW_VENDORS,
    PERMISSIONS.VIEW_HELP,
    PERMISSIONS.VIEW_INBOX,
    PERMISSIONS.VIEW_INSIGHTS,
  ],
  employee: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_EXPENSES,
    PERMISSIONS.VIEW_CARD_TRANSACTIONS,
    PERMISSIONS.VIEW_REIMBURSEMENTS,
    PERMISSIONS.VIEW_TRAVEL_EXPENSES,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.MANAGE_PERSONAL_SETTINGS,
    PERMISSIONS.VIEW_HELP,
    PERMISSIONS.VIEW_INBOX,
    PERMISSIONS.VIEW_EMPLOYEE_DASHBOARD
  ],
};

