"use client";

import { Button } from "@/components/ui/button";
import { ArrowRight, Loader2, Upload, X, Briefcase, Globe, Phone, Link as LinkIcon } from "lucide-react";
import { useRouter } from "next/navigation";
import {
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  Form,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import z from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import OnboardingTitle from "@/components/onboarding/_shared/OnboardingTitle";
import { useOnboardingStore } from "@/stores/useVilletoStore";
import { Building03FreeIcons } from "@hugeicons/core-free-icons";

import { HugeiconsIcon } from "@hugeicons/react";
import { toast } from "sonner";
import { useUpdateOnboardingCompanyDetailsApi } from "@/actions/onboarding/update-onboarding-company-details.ts";
import FormFieldSelect from "@/components/form fields/formFieldSelect";
import FormFieldInput from "@/components/form fields/formFieldInput";
import FormFieldLogoUpload from "@/components/form fields/formFieldLogoUpload";
import { useEffect } from "react";
import { onboardingBusinessSchema } from "@/lib/schemas/schemas";
import Image from "next/image";
import { useHydrateOnboardingData } from "@/hooks/useHydrateOnboardingData";

export default function Business() {
  const router = useRouter();
  const { businessSnapshot, updateBusinessSnapshot, preOnboarding } =
    useOnboardingStore();
  useHydrateOnboardingData();
  const updateOnboarding = useUpdateOnboardingCompanyDetailsApi();
  const loading = updateOnboarding.isPending;

  const form = useForm({
    resolver: zodResolver(onboardingBusinessSchema),
    mode: "onChange",
    defaultValues: {
      business_name: "",
      contactPhone: businessSnapshot.contactNumber || "",
      countryOfRegistration: businessSnapshot.countryOfRegistration || "",
      websiteUrl: businessSnapshot.website || "",
      businessLogo: businessSnapshot.logo || undefined,
    },
  });

  useEffect(() => {
    // Filter out auto-generated business names (e.g. "user@email.com Group")
    const isAutoGenerated = businessSnapshot.businessName?.includes("@");
    form.reset({
      business_name: isAutoGenerated ? "" : (businessSnapshot.businessName || ""),
      contactPhone: businessSnapshot.contactNumber || "",
      countryOfRegistration: businessSnapshot.countryOfRegistration || "",
      websiteUrl: businessSnapshot.website || "",
      businessLogo: businessSnapshot.logo || undefined,
    });
  }, [businessSnapshot, form]);

    async function onSubmit(data: z.infer<typeof onboardingBusinessSchema>) {
    try {
      const payload = {
        ...data,
        companyName: data.business_name,
      };
      const response = await updateOnboarding.mutateAsync(payload);

      // Convert logo file to base64 for local storage if it's a File
      // The API action handles conversion for API submission
      let logoUrl: string | undefined = undefined;
      if (data.businessLogo instanceof File) {
        logoUrl = await new Promise<string>((resolve, reject) => {
          const reader = new FileReader();
          reader.onloadend = () => resolve(reader.result as string);
          reader.onerror = reject;
          reader.readAsDataURL(data.businessLogo as File);
        });
      } else if (typeof data.businessLogo === "string") {
        logoUrl = data.businessLogo;
      } else if (response?.data?.logo) {
        // Use logo from API response if available
        logoUrl = response.data.logo as string;
      }

      // Update the store with form data
      updateBusinessSnapshot({
        businessName: data.business_name,
        contactNumber: data.contactPhone,
        countryOfRegistration: data.countryOfRegistration,
        website: data.websiteUrl,
        logo: logoUrl, // Save logo to businessSnapshot
      });

      router.push("/onboarding/leadership");
    } catch (e: unknown) {
      console.warn(e);
      const error = e as { response?: { data?: { message?: string } } };
      toast.error(
        error.response?.data?.message || "Failed to update company details"
      );
    }
  }

  return (
    <div className="space-y-8 flex flex-col justify-start h-full py-4">
      <div className="text-left ">
        <div className="w-16 h-16 bg-primary-light rounded-full flex mb-10">
          <HugeiconsIcon
            icon={Building03FreeIcons}
            className="size-16 text-primary"
          />
        </div>

        <OnboardingTitle
          title="Tell us more about your Business"
          subtitle="
                    Tell us about your business"
        />
      </div>
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 mt-4">
          <FormFieldLogoUpload
            control={form.control}
            name="businessLogo"
            label="Business Logo"
            description=""
            maxSize={1 * 1024 * 1024}
            variant="button"
          />

          <FormField
            control={form.control}
            name="business_name"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Business Name<span className="text-destructive">*</span></FormLabel>
                <FormControl>
                    <div className="relative">
                        <div className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400">
                            <Briefcase className="h-5 w-5" />
                        </div>
                        <Input
                            {...field}
                            placeholder="Enter your business name"
                             className="pl-10 text-gray-600 bg-gray-50 border-gray-200"
                        />
                    </div>
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormFieldSelect
            control={form.control}
            name="countryOfRegistration"
            label="Country of Registration"
            values={[
              { label: "Kenya", value: "KYA" },
              { label: "Ghana", value: "GHN" },
              { label: "Nigeria", value: "NGA" },
            ]}
            placeholder="Select Country"
            prefixIcon={<Globe className="h-5 w-5 text-gray-400" />}
          />

          <FormFieldInput
            control={form.control}
            name="contactPhone"
            label="Contact Number"
            placeholder="+1"
            prefixIcon={<Phone className="h-5 w-5 text-gray-400" />}
          />

          <FormFieldInput
            control={form.control}
            name="websiteUrl"
            label="Website"
            placeholder="Enter your website link"
            type="text"
            prefixIcon={<LinkIcon className="h-5 w-5 text-gray-400" />}
          />

          {/* <FormField control={form.control} name="password"
                    render={({ field }) => (
                        <FormItem>
                            <FormLabel>Password</FormLabel>
                            <FormControl>

                                <Input type="password" {...field} />
                            </FormControl>
                            <FormMessage />
                        </FormItem>
                    )} />

                <div className="grid grid-cols-2 gap-3">

                    <FormField control={form.control} name="currency"
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>Currency</FormLabel>
                                <Select onValueChange={field.onChange} defaultValue={field.value} >
                                    <FormControl>
                                        <SelectTrigger>
                                            <SelectValue placeholder="Select a country" />
                                        </SelectTrigger>
                                    </FormControl>           <SelectContent>

                                        <SelectItem value="USD">USD</SelectItem>
                                        <SelectItem value="NGN">NGN</SelectItem>
                                    </SelectContent>
                                </Select>
                                <FormMessage />
                            </FormItem>
                        )} />
                </div> */}

          <div className="w-full flex mt-10">
            <Button
              type="submit"
              className="ml-auto! min-w-[250px] max-w-[250px] self-end"
              disabled={loading}
            >
              {loading ? "Creating..." : "Continue"}{" "}
              {loading ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <ArrowRight className="h-4 w-4" />
              )}
            </Button>
          </div>
        </form>
      </Form>
    </div>
  );
}
