import { useEffect, useRef } from "react";
import { useOnboardingStore } from "@/stores/useVilletoStore";
import {
    useGetOnboardingDetailsApi,
    type Onboarding,
} from "@/queries/pre-onboarding/get-onboarding-details";

type Company = Onboarding["company"];
type Owner = NonNullable<Company["owners"]>[number];
type BusinessOwner = NonNullable<Onboarding["businessOwners"]>[number];
type ControllingOfficer = NonNullable<Company["controllingOfficers"]>[number];

/**
 * Fetches onboarding details from the API and hydrates the Zustand store.
 * Call this hook at the top of each onboarding page so that data persists
 * across navigation and page refresh.
 */
export const useHydrateOnboardingData = () => {
    const {
        onboardingId,
        businessSnapshot,
        updateBusinessSnapshot,
        updateUserProfiles,
        contactEmail,
        setSelfOwner,
    } = useOnboardingStore();

    const hasHydrated = useRef(false);

    const { data, isLoading, isError } = useGetOnboardingDetailsApi(
        onboardingId,
        { enabled: !!onboardingId }
    );

    useEffect(() => {
        if (!data?.data || hasHydrated.current) return;

        const onboarding = data.data;
        const company = onboarding.company;

        // Hydrate business snapshot
        const rawCompanyName = company.companyName || "";
        const rawLegalName = company.businessName || company.companyName || "";
        // Filter out auto-generated names that contain the user's email address
        const isCompanyNameAutoGenerated = rawCompanyName.includes("@");
        const isLegalNameAutoGenerated = rawLegalName.includes("@");
        
        const localSnapshot = useOnboardingStore.getState().businessSnapshot;
        updateBusinessSnapshot({
            businessName: localSnapshot.businessName || (isCompanyNameAutoGenerated ? "" : rawCompanyName),
            legalName: localSnapshot.legalName || (isLegalNameAutoGenerated ? "" : rawLegalName),
            registeredAddress: localSnapshot.registeredAddress || company.address || "",
            taxId: localSnapshot.taxId || company.taxId || undefined,
            registrationId: localSnapshot.registrationId || company.registrationId || undefined,
            contactNumber: localSnapshot.contactNumber || company.contactPhone || "",
            countryOfRegistration: localSnapshot.countryOfRegistration || company.countryOfRegistration || "",
            website: localSnapshot.website || company.websiteUrl || "",
            logo: localSnapshot.logo || company.logo || company.logoUrl || undefined,
        });

        // Hydrate leadership (businessOwners/owners + controlling officers → userProfiles)
        // Check for businessOwners at top level first, fallback to company.owners
        const apiOwners = onboarding.businessOwners && onboarding.businessOwners.length > 0 
            ? onboarding.businessOwners 
            : (company.owners || []);
            
        const ownerProfiles = apiOwners.map((owner: any) => ({
            id: owner.userId || owner.ownerId || owner.user?.userId || Date.now().toString(),
            firstName: owner.firstName || owner.user?.firstName || "",
            lastName: owner.lastName || owner.user?.lastName || "",
            email: owner.email || owner.user?.email || "",
            role: owner.position || owner.user?.role || "OWNER",
            phone: (owner.phone === "00000000000" ? undefined : owner.phone) || (owner.user?.phone === "00000000000" ? undefined : owner.user?.phone) || undefined,
            ownershipPercentage: typeof owner.ownershipPercentage === 'string' ? parseFloat(owner.ownershipPercentage) : owner.ownershipPercentage,
        }));

        const officerProfiles = (company.controllingOfficers || []).map((officer: ControllingOfficer) => ({
            id: officer.controllingOfficerId || officer.user?.userId || Date.now().toString(),
            firstName: officer.user?.firstName || "",
            lastName: officer.user?.lastName || "",
            email: officer.user?.email || "",
            role: officer.user?.role || "",
        }));

        type HydratedProfile = {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            role: string;
            phone?: string;
            ownershipPercentage?: number;
        };

        const profileMap = new Map<string, HydratedProfile>();
        const mergedProfiles: HydratedProfile[] = [
            ...ownerProfiles,
            ...officerProfiles.map(o => ({ ...o, ownershipPercentage: undefined as number | undefined })),
        ];
        mergedProfiles.forEach(profile => {
            const key = profile.email || profile.id;
            if (profileMap.has(key)) {
                const existing = profileMap.get(key)!;
                profileMap.set(key, {
                    ...existing,
                    ...profile,
                    ownershipPercentage: existing.ownershipPercentage ?? profile.ownershipPercentage,
                    role: existing.role || profile.role,
                });
            } else {
                profileMap.set(key, profile);
            }
        });

        const allProfiles = Array.from(profileMap.values());
        
        // Extract selfOwner if they are the applicant
        const selfProfileIndex = allProfiles.findIndex(p => p.email && contactEmail && p.email.toLowerCase() === contactEmail.toLowerCase());
        
        if (selfProfileIndex !== -1) {
            const selfProfile = allProfiles[selfProfileIndex];
            if (selfProfile.ownershipPercentage !== undefined) {
                setSelfOwner({
                    firstName: selfProfile.firstName,
                    lastName: selfProfile.lastName,
                    email: selfProfile.email,
                    ownershipPercentage: selfProfile.ownershipPercentage
                });
            }
            // Remove self from userProfiles to avoid duplication
            allProfiles.splice(selfProfileIndex, 1);
        }

        if (allProfiles.length > 0) {
            updateUserProfiles(allProfiles);
        } else {
            updateUserProfiles([]);
        }

        // Hydrate financial pulse (spend limit)
        const spendLimit = company.spendLimit;
        if (spendLimit) {
            const ranges = [
                { value: 0, label: "<$10k", lower: 0 },
                { value: 1, label: "$10k-$50k", lower: 10000 },
                { value: 2, label: "$50k-$200k", lower: 50000 },
                { value: 3, label: "$200k+", lower: 200000 },
            ];

            const foundRange = ranges.find(r => r.lower === spendLimit.lower);
            if (foundRange) {
                // Update top-level financial state
                useOnboardingStore.setState({
                    monthlySpend: foundRange.value,
                    spendRange: foundRange.label
                });
                
                // Update financialPulse.monthlySpend for Review page display
                const store = useOnboardingStore.getState();
                store.updateFinancialPulse({
                    monthlySpend: foundRange.label
                });
            }
        }

        // Hydrate products — only if user hasn't already made local selections
        // (e.g. via toggleProduct on the products page, which saves to cookies).
        // This prevents stale API cache data from overwriting fresh local selections.
        const store = useOnboardingStore.getState();
        const hasLocalSelections = store.villetoProducts.some((p) => p.selected);
        const apiModules: string[] = [...(company.productModules ?? [])];
        if (apiModules.length > 0 && !hasLocalSelections) {
            const updatedProducts = store.villetoProducts.map((product) => ({
                ...product,
                selected: apiModules.includes(product.value),
            }));
            useOnboardingStore.setState({ villetoProducts: updatedProducts });
        }

        hasHydrated.current = true;
    }, [data, businessSnapshot.logo, updateBusinessSnapshot, updateUserProfiles]);

    return { isLoading, isError, data };
};
