"use client"

import { cn } from "@/lib/utils";
import { usePathname, useRouter } from "next/navigation";
import { useOnboardingStore } from "@/stores/useVilletoStore";

import { ONBOARDING_STEPS as steps } from "@/lib/constants/onboarding-steps";

const getInitials = (name: string) => {
  if (!name) return "";
  const words = name.trim().split(" ");
  if (words.length >= 2) {
    return (words[0][0] + words[1][0]).toUpperCase();
  }
  return name.substring(0, 2).toUpperCase();
};

export const OnboardingSidebar = () => {
    const pathName = usePathname();
    const router = useRouter();
    const { stoppedAtStep, businessSnapshot } = useOnboardingStore();

    // Filter out auto-generated names like "user@email.com Group"
    const isAutoGenerated = businessSnapshot.businessName?.includes("@");
    const displayBusinessName = isAutoGenerated ? "" : (businessSnapshot.businessName || "");

    // Compute currentStep once, outside the map
    const pathSegment = pathName?.split("/").pop();
    const isVerifyOtp = pathName?.includes('verify-otp');
    const currentStepObj = steps.find(s => s.key === pathSegment);
    let currentStep = currentStepObj?.id || 0;
    if (currentStep === 0 && isVerifyOtp) {
        currentStep = stoppedAtStep || 1;
    }
    const isStep3OrLater = currentStep >= 3;

    // Function to handle step click
    const handleStepClick = (stepKey: string, stepId: number) => {
        // Only navigate if the step is completed (stepId < currentStep)
        if (stepId < currentStep) {
            if (stepId == 1) {
                router.push(`/onboarding`);
                return;
            }
            router.push(`/onboarding/${stepKey}`);
        }
    };

    return (
        <div className="flex-1 max-w-[660px] h-full bg-contain bg-no-repeat rounded-[30px] relative overflow-hidden" style={{ backgroundImage: "url('/onboarding-layout.webp')" }}>

            <img src="/onboarding-layout.webp" className="h-full w-full rounded-[30px]" />
            {/* Overlay */}
            <div className="bg-navy/80 absolute p-8 top-0 bottom-0 left-0 right-0 w-full h-full flex flex-col rounded-[30px]">

                {/* Logo / Business branding — rendered ONCE above the step list */}
                {isStep3OrLater ? (
                    <div className="mb-8 flex items-center gap-3">
                        {businessSnapshot.logo ? (
                            <img src={businessSnapshot.logo} alt="Company Logo" className="h-10 w-10 object-contain rounded-full bg-white border border-white/20" />
                        ) : (
                            <div className="h-10 w-10 flex items-center justify-center rounded-full bg-primary text-white font-semibold text-sm border border-white/20">
                                {getInitials(displayBusinessName)}
                            </div>
                        )}
                        <span className="text-white font-medium text-lg leading-tight truncate max-w-[200px]">
                            {displayBusinessName || "Your Business"}
                        </span>
                    </div>
                ) : (
                    <div className="mb-8">
                        <img src="/images/logo.png" className="h-16 w-40 object-cover" alt="Villeto Logo" />
                    </div>
                )}

                {/* Steps */}
                <div className="flex flex-col gap-1.5 flex-1">
                    {steps.map((step, index) => {
                        const isCurrent = step.key === pathSegment || (step.id === 1 && isVerifyOtp);
                        const isCompleted = step.id < currentStep && !isVerifyOtp;
                        const isUpcoming = currentStep + 1;

                        return (
                            <div key={step.id}>
                                <div
                                    className={cn(
                                        "flex items-start gap-5",
                                    {
                                        "cursor-pointer hover:opacity-80 transition-opacity": isCompleted,
                                        "cursor-default": !isCompleted
                                    }
                                )}
                                onClick={() => handleStepClick(step.key, step.id)}
                            >
                                {/* Step indicator */}
                                <div className="flex flex-col items-center gap-1.5">
                                    <div
                                        className={cn(
                                            "w-9 h-9 rounded-full flex items-center justify-center text-sm font-medium transition-colors border border-gray-600",
                                            {
                                                "bg-primary text-white border-0": isCompleted,
                                                "bg-transparent text-white border border-primary": isUpcoming === step.id || currentStep === step.id,
                                            }
                                        )}
                                    >
                                        <div className={cn("w-5 h-5 rounded-full bg-gray-600 border border-gray-600", {
                                            "bg-navy text-white": isCompleted,
                                            "bg-primary text-white border-primary border": (isUpcoming != step.id) && isCurrent,
                                        })} />
                                    </div>
                                    {/* Connector line */}
                                    {index < steps.length - 1 && (
                                        <div className="w-px h-9 bg-gray-500 mt-2" />
                                    )}
                                </div>

                                {/* Step content */}
                                <div className="flex-1 ">
                                    <div className="text-sm leading-[100%] text-white mb-2.5">
                                        STEP {step.id}
                                    </div>
                                    <div
                                        className={cn(
                                            "text-lg leading-[100%] font-semibold ",
                                            "text-white"
                                        )}
                                    >
                                        {step.title}
                                    </div>
                                </div>
                            </div>
                        </div>
                        );
                    })}
                </div>
            </div>
        </div>
    );
};